story book formly stepper
GSA/sam-design-system pull request #1265
Opened 2023-07-17 18:23 UTC by shayan-roshan

sb formly stepper demo

## Description

## Motivation and Context

## Type of Change (Select One and Apply Github Label)

- [ ] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [ ] New feature (non-breaking change which adds functionality) -> Apply enhancement label
- [ ] Breaking change (fix or feature that would cause existing functionality to change) -> Apply breaking label

## Screenshots (if appropriate):

## Which browsers have you tested?
- [ ] Internet Explorer 11
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

## Checklist:

- [ ] I have read the (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md] document.
- [ ] My code passes the automated linter.
- [ ] This code has been reviewed by another team member and passes the reviewer checklist found in (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md]
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code is 508 compliant as tested by AMP and JAWS
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-17 18:42 UTC, cwolf10 requested changes

2023-07-17 18:42 UTC, cwolf10 commented on libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper.stories.ts
> +    label: templateOptions,
Can remove these argTypes

2023-07-17 18:42 UTC, cwolf10 commented on libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper.stories.ts
> +export const USWDS: Story = (args) => ({
Stackblitz fails:
ERROR
Error: R3InjectorError(AppModule)[Router -> Router -> Router]:
NullInjectorError: No provider for Router!

2023-07-17 18:42 UTC, cwolf10 commented on libs/documentation/src/lib/storybook/formly/formly-stepper/formly-stepper.stories.ts
> +  preview: generateConfig(
Stackblitz is failing to initialize:
Error in src/app/formly-stepper-advanced.component.html (49:57)
Type '{ key: string; templateOptions: { placeholder: string; }; fieldGroup: ({ key: string; fieldGroupClassName: string; fieldGroup: ({ className: string; key: string; type: string; templateOptions: { ...; }; } | { ...; })[]; className?: undefined; type?: undefined; templateOptions?: undefined; modelOptions?: undefined; }...' is not assignable to type 'FormlyFieldConfig'.
Types of property 'fieldGroup' are incompatible.
Type '({ key: string; fieldGroupClassName: string; fieldGroup: ({ className: string; key: string; type: string; templateOptions: { label: string; hideOptional: boolean; options: { label: string; value: string; }[]; required: boolean; showError?: undefined; }; } | { ...; })[]; className?: undefined; type?: undefined; templ...' is not assignable to type 'FormlyFieldConfig[]'.
Type '{ key: string; fieldGroupClassName: string; fieldGroup: ({ className: string; key: string; type: string; templateOptions: { label: string; hideOptional: boolean; options: { label: string; value: string; }[]; required: boolean; showError?: undefined; }; } | { ...; })[]; className?: undefined; type?: undefined; templa...' is not assignable to type 'FormlyFieldConfig'.
Type '{ className: string; type: string; key: string; templateOptions: { label: string; required: boolean; showError: boolean; }; modelOptions: { updateOn: string; }; fieldGroupClassName?: undefined; fieldGroup?: undefined; }' is not assignable to type 'FormlyFieldConfig'.
The types of 'modelOptions.updateOn' are incompatible between these types.
Type 'string' is not assignable to type '"blur" | "change" | "submit"'.

2023-08-14 14:14 UTC, cwolf10 commented
Looks like the nav buttons introduced some lint issues. Also, did you manage to get the stackblitzes updated? It looks like the only update pushed since my last comment was the update to the nav buttons.

2023-08-14 14:34 UTC, shayan-roshan commented
this is not a final version of the branch that is good to be merged, i just made a commit to save some changes. 
I am still waiting on the final changes that need to be made on the pill buttons icons and then I will update the stepper.

2023-08-14 15:19 UTC, cwolf10 commented
All good, just wanted to make sure I wasn't blocking getting this merged.

2024-10-09 17:11 UTC, closed without merging