Access Assistant checks on sam formly and layouts library
GSA/sam-design-system pull request #521
Opened 2021-01-26 17:32 UTC by Bibek-Regmi

More accessibility related changes - Most were documentation side rather than the library itself.

## Type of Change (Select One and Apply Github Label)

- [x] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [ ] New feature (non-breaking change which adds functionality) -> Apply enhancement label
- [ ] Breaking change (fix or feature that would cause existing functionality to change) -> Apply breaking label

## Screenshots (if appropriate):

## Which browsers have you tested?
- [ ] Internet Explorer 11
- [ ] Edge
- [x] Chrome
- [ ] Firefox
- [ ] Safari

## Checklist:

- [ ] I have read the (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md] document.
- [ ] My code passes the automated linter.
- [ ] This code has been reviewed by another team member and passes the reviewer checklist found in (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md]
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code is 508 compliant as tested by AMP and JAWS
- [ ] Any dependent changes have been merged and published in downstream modules

2021-01-26 19:37 UTC, cwolf10 requested changes

2021-01-26 19:37 UTC, cwolf10 commented on libs/packages/components/src/lib/text/text.component.ts
> +    console.log(this);
Remove this log statement.

2021-01-26 21:22 UTC, Bibek-Regmi commented on libs/packages/components/src/lib/text/text.component.ts
> +    console.log(this);
Updated!

2021-01-27 15:33 UTC, yerramshilpa approved these changes

2021-01-27 17:02 UTC, merged