IAE-66449: Update data-entry stepper implementation for sub-steps
GSA/sam-design-system pull request #937
Opened 2022-03-25 13:14 UTC by cwolf10

## Description
Updated the demo code for the custom uswds stepper to allow for substeps. Substeps can be added by providing a sds-step as a child of the main sds-steps.

## Motivation and Context
https://cm-jira.usa.gov/browse/IAEDEV-66449

## Type of Change (Select One and Apply Github Label)

- [ ] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [x] New feature (non-breaking change which adds functionality) -> Apply enhancement label
- [ ] Breaking change (fix or feature that would cause existing functionality to change) -> Apply breaking label

## Screenshots (if appropriate):

<img width="992" alt="Screen Shot 2022-03-25 at 9 10 01 AM" src="https://user-images.githubusercontent.com/72805180/160126772-ac147c78-768a-4e74-be93-05a9d9c82c74.png">

## Which browsers have you tested?
- [ ] Internet Explorer 11
- [ ] Edge
- [x] Chrome
- [x] Firefox
- [x] Safari

## Checklist:

- [ ] I have read the (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md] document.
- [ ] My code passes the automated linter.
- [ ] This code has been reviewed by another team member and passes the reviewer checklist found in (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md]
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code is 508 compliant as tested by AMP and JAWS
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-25 13:32 UTC, yerramshilpa submitted a review, later dismissed

2022-04-01 22:35 UTC, yerramshilpa approved these changes

2022-04-11 13:54 UTC, yerramshilpa approved these changes

2022-04-18 17:36 UTC, davereed requested changes

2022-04-18 17:36 UTC, davereed commented on libs/documentation/src/lib/components/formly-stepper/demos/uswds-stepper/uswds-custom-stepper.component.ts
> +import { SdsStepComponent, SdsStepper } from "../../../../../../../packages/sam-formly/src/lib/formly-stepper/sds-stepper";
don't use the relative/full path

2022-04-18 17:50 UTC, cwolf10 commented on libs/documentation/src/lib/components/formly-stepper/demos/uswds-stepper/uswds-custom-stepper.component.ts
> +import { SdsStepComponent, SdsStepper } from "../../../../../../../packages/sam-formly/src/lib/formly-stepper/sds-stepper";
Fixed the import

2022-04-18 17:56 UTC, davereed approved these changes

2022-04-18 17:56 UTC, merged