Stepper space for multi checkbox
GSA/sam-design-system pull request #960
Opened 2022-04-21 14:05 UTC by yerramshilpa

## Description

## Motivation and Context

## Type of Change (Select One and Apply Github Label)

- [ ] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [ ] New feature (non-breaking change which adds functionality) -> Apply enhancement label
- [ ] Breaking change (fix or feature that would cause existing functionality to change) -> Apply breaking label

## Screenshots (if appropriate):

## Which browsers have you tested?
- [ ] Internet Explorer 11
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

## Checklist:

- [ ] I have read the (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md] document.
- [ ] My code passes the automated linter.
- [ ] This code has been reviewed by another team member and passes the reviewer checklist found in (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md]
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code is 508 compliant as tested by AMP and JAWS
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-21 14:34 UTC, cwolf10 requested changes
Can you remove these whitespace changes? Most of the line splitting there wasn't even anything new added. It just makes the PR harder to understand and if we ever need to go back and track changes to these files it makes that process harder and take longer.

2022-04-22 13:25 UTC, yerramshilpa commented on libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.ts
> +    persission: {
Name corrected

2022-04-22 13:25 UTC, yerramshilpa commented on libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.html
> +    <sds-step id="persission" text="persission" [fieldConfig]="stepMap.persission.fieldConfig">
Name corrected

2022-05-03 19:26 UTC, cwolf10 approved these changes

2022-05-03 19:29 UTC, merged